# robbyrussell theme

format = """
$character\
$directory\
$git_branch\
$git_status"""

add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
truncation_length = 1
read_only = ''

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '


[git_status]
format = '([$modified$ahead_behind]($style) )'
style = "bold yellow"

modified = "✗"

staged = ""
untracked = ""
conflicted = ""
renamed = ""
deleted = ""
stashed = ""

ahead = ""
behind = ""
diverged = ""
