#["personal/dev/env/dot_config/nvim"]
#    type = "git-repo"
#    url = "git@github.com:LuckyBastrd/init.lua.git"
#    refreshPeriod = "24h"

#["personal/dev/env/private_dot_local/bin/scripts/external_tmux-sessionizer"]
#    type = "git-repo"
#    url = "git@github.com:LuckyBastrd/tmux-sessionizer.git"
#    refreshPeriod = "168h"

# [".local/scripts/tmux-sessionizer"]
#     type = "file"
#     url = "https://raw.githubusercontent.com/ThePrimeagen/tmux-sessionizer/refs/heads/master/tmux-sessionizer"
#     refreshPeriod = "168h"
#     executable = true

# [".oh-my-zsh"]
#     type = "archive"
#     url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
