#["personal/dev/env/dot_config/nvim"]
#    type = "git-repo"
#    url = "git@github.com:LuckyBastrd/init.lua.git"
#    refreshPeriod = "24h"

#["personal/dev/env/private_dot_local/bin/scripts/external_tmux-sessionizer"]
#    type = "git-repo"
#    url = "git@github.com:LuckyBastrd/tmux-sessionizer.git"
#    refreshPeriod = "168h"
